In [1]:
# numpy import
import numpy as np

In [2]:
# word embedding:  dictionary that maps word indexes to weights (numbers)
embedding = {i: np.random.normal(0, .1, 10) for i in range(10001)}

In [3]:
# observe what it is
embedding

{0: array([-0.13448781, -0.06214779,  0.02200893,  0.12768878,  0.03179707,
         0.00928053, -0.06904167,  0.16417705,  0.00799456,  0.1706489 ]),
 1: array([-0.0667546 , -0.05176666,  0.04672455, -0.08769408, -0.0055222 ,
        -0.25600054, -0.18852691,  0.10354632,  0.07355787, -0.17299365]),
 2: array([ 0.06071694, -0.03577688, -0.06151389,  0.04596833, -0.02993192,
        -0.05653512, -0.06296081, -0.12185353, -0.15508381, -0.00097578]),
 3: array([ 0.02296884,  0.14474329, -0.06970482, -0.13961618, -0.10587921,
         0.14439126,  0.07144804,  0.14946498, -0.21125283,  0.03736222]),
 4: array([ 0.02081456,  0.17555871, -0.01147591,  0.10580177, -0.14735259,
        -0.00717077, -0.03431158,  0.21199338,  0.07285117, -0.12199624]),
 5: array([ 0.14031251, -0.04289061,  0.15540839, -0.00061207,  0.1221161 ,
        -0.02523737, -0.15107261, -0.04308672, -0.03875751,  0.07009699]),
 6: array([-0.02674075,  0.0709388 ,  0.10460759,  0.05227037,  0.06507292,
        -0.0201971

In [4]:
# sample data sequences
sequence1 = [1, 13, 24, 12, 55, 1, 2, 3]
sequence2 = [2, 24, 15, 23, 3, 2, 1, 5]

In [5]:
# sample data point to hold our data
dat_point1 = np.zeros((8, 10))

In [6]:
# empty zeroes
dat_point1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
# fill each row with the weight for each corresponding word
for idx, val in enumerate(sequence1):
    dat_point1[idx] = embedding[val]

In [8]:
# this is the result that we get
dat_point1

array([[-0.0667546 , -0.05176666,  0.04672455, -0.08769408, -0.0055222 ,
        -0.25600054, -0.18852691,  0.10354632,  0.07355787, -0.17299365],
       [-0.00793758, -0.16797261, -0.1596059 , -0.07607895,  0.03904501,
        -0.02585357, -0.01872852,  0.07253528,  0.14006073, -0.04785893],
       [ 0.09000934,  0.02501001, -0.134581  ,  0.03716898, -0.06644751,
        -0.03712858,  0.09129684,  0.0533453 ,  0.01870462,  0.106052  ],
       [-0.02815036,  0.05886928, -0.12075338,  0.13943753,  0.12598419,
         0.07955445, -0.0145978 ,  0.08839495, -0.00474339,  0.00894752],
       [ 0.05723384, -0.03736214, -0.1462395 ,  0.16796107,  0.07155532,
        -0.04846198, -0.16151823, -0.18088105,  0.06796759,  0.03770475],
       [-0.0667546 , -0.05176666,  0.04672455, -0.08769408, -0.0055222 ,
        -0.25600054, -0.18852691,  0.10354632,  0.07355787, -0.17299365],
       [ 0.06071694, -0.03577688, -0.06151389,  0.04596833, -0.02993192,
        -0.05653512, -0.06296081, -0.12185353

In [9]:
# notice how the word indices match the embedding weights
embedding[1]

array([-0.0667546 , -0.05176666,  0.04672455, -0.08769408, -0.0055222 ,
       -0.25600054, -0.18852691,  0.10354632,  0.07355787, -0.17299365])

In [10]:
# function to 
def create_word_matrix(sequence, embedding, embedding_dim=10):
    data_point = np.zeros((len(sequence), embedding_dim))
    for idx, val in enumerate(sequence):
        data_point[idx] = embedding[val]
        
    return data_point

In [11]:
create_word_matrix(sequence1, embedding, 10)

array([[-0.0667546 , -0.05176666,  0.04672455, -0.08769408, -0.0055222 ,
        -0.25600054, -0.18852691,  0.10354632,  0.07355787, -0.17299365],
       [-0.00793758, -0.16797261, -0.1596059 , -0.07607895,  0.03904501,
        -0.02585357, -0.01872852,  0.07253528,  0.14006073, -0.04785893],
       [ 0.09000934,  0.02501001, -0.134581  ,  0.03716898, -0.06644751,
        -0.03712858,  0.09129684,  0.0533453 ,  0.01870462,  0.106052  ],
       [-0.02815036,  0.05886928, -0.12075338,  0.13943753,  0.12598419,
         0.07955445, -0.0145978 ,  0.08839495, -0.00474339,  0.00894752],
       [ 0.05723384, -0.03736214, -0.1462395 ,  0.16796107,  0.07155532,
        -0.04846198, -0.16151823, -0.18088105,  0.06796759,  0.03770475],
       [-0.0667546 , -0.05176666,  0.04672455, -0.08769408, -0.0055222 ,
        -0.25600054, -0.18852691,  0.10354632,  0.07355787, -0.17299365],
       [ 0.06071694, -0.03577688, -0.06151389,  0.04596833, -0.02993192,
        -0.05653512, -0.06296081, -0.12185353

In [12]:
# wrap up our sequences in a list
sequences = [sequence1, sequence2]

In [13]:
# final matrix to hold our embedding data
word_data = np.zeros((2, 8, 10))

In [14]:
# fill in each row of the dataset with the encoded embedding data
for idx, row in enumerate(word_data):
    word_data[idx] = create_word_matrix(sequences[idx], embedding)

In [15]:
# this is what a single data point would look like
word_data[0]

array([[-0.0667546 , -0.05176666,  0.04672455, -0.08769408, -0.0055222 ,
        -0.25600054, -0.18852691,  0.10354632,  0.07355787, -0.17299365],
       [-0.00793758, -0.16797261, -0.1596059 , -0.07607895,  0.03904501,
        -0.02585357, -0.01872852,  0.07253528,  0.14006073, -0.04785893],
       [ 0.09000934,  0.02501001, -0.134581  ,  0.03716898, -0.06644751,
        -0.03712858,  0.09129684,  0.0533453 ,  0.01870462,  0.106052  ],
       [-0.02815036,  0.05886928, -0.12075338,  0.13943753,  0.12598419,
         0.07955445, -0.0145978 ,  0.08839495, -0.00474339,  0.00894752],
       [ 0.05723384, -0.03736214, -0.1462395 ,  0.16796107,  0.07155532,
        -0.04846198, -0.16151823, -0.18088105,  0.06796759,  0.03770475],
       [-0.0667546 , -0.05176666,  0.04672455, -0.08769408, -0.0055222 ,
        -0.25600054, -0.18852691,  0.10354632,  0.07355787, -0.17299365],
       [ 0.06071694, -0.03577688, -0.06151389,  0.04596833, -0.02993192,
        -0.05653512, -0.06296081, -0.12185353

In [17]:
word_data[0].shape

(8, 10)

In [18]:
dense_layer = np.random.normal(0, 1, size=(10, 50))

In [19]:
dense_layer

array([[-1.00345319e+00,  1.08567900e+00,  5.21598124e-02,
        -7.45079153e-01, -4.09661605e-02, -9.22065374e-02,
         2.53619278e-01, -8.28609948e-01,  2.73867344e-01,
        -3.04164293e-01, -1.33097631e+00, -2.43957147e-01,
        -1.02963329e+00, -9.19871066e-01, -4.80986731e-01,
        -6.33426609e-01,  8.11918219e-01,  4.58677041e-01,
         1.36007807e-02,  4.62329160e-01, -1.57135266e+00,
        -7.18886164e-02,  4.10541394e-01,  1.11955066e+00,
         2.45150278e+00, -7.29410816e-02,  1.59585088e-01,
         6.05405978e-01,  1.84466080e+00, -7.95304252e-01,
        -4.66515410e-01,  8.68250275e-01, -5.52734176e-01,
        -1.29890638e-01,  8.66661885e-03,  9.82279475e-01,
         4.86951368e-01, -2.13561898e+00, -6.72193693e-01,
        -3.06141260e-01, -1.70127707e+00, -6.24495679e-01,
        -6.99900157e-01,  3.85922303e-01, -8.10230853e-01,
        -2.66569724e-01, -1.98237624e+00, -1.07737731e+00,
         3.26254169e-01,  3.07693709e-01],
       [-1.71

In [21]:
np.maximum(word_data[0].dot(dense_layer), 0)

array([[4.17736563e-01, 2.46349319e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 4.21592076e-01, 0.00000000e+00, 0.00000000e+00,
        2.94242365e-01, 1.11916087e-01, 2.50958388e-01, 0.00000000e+00,
        1.34978166e-01, 4.15267818e-01, 3.83711801e-02, 5.76026670e-02,
        0.00000000e+00, 0.00000000e+00, 3.15585641e-01, 0.00000000e+00,
        0.00000000e+00, 1.78565856e-01, 0.00000000e+00, 1.59960445e-01,
        0.00000000e+00, 4.40415508e-02, 1.78807581e-01, 0.00000000e+00,
        0.00000000e+00, 5.18819889e-02, 7.97031816e-01, 0.00000000e+00,
        6.81217831e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        6.96789010e-02, 4.76043972e-01, 0.00000000e+00, 0.00000000e+00,
        7.02505574e-01, 0.00000000e+00, 4.83000431e-01, 6.30736690e-01,
        1.80126670e-01, 0.00000000e+00, 3.83684620e-01, 4.63452966e-01,
        0.00000000e+00, 0.00000000e+00],
       [4.30310812e-01, 3.08346299e-02, 0.00000000e+00, 6.87368383e-02,
        0.00000000e+00,

In [22]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [23]:
sigmoid(5)

0.9933071490757153

In [24]:
sigmoid(-11)

1.670142184809518e-05

In [25]:
sigmoid(0)

0.5